[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

[dev]
  command = "vite"
  port = 5173
  targetPort = 5173
  framework = "vite"

[redirects]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
